package entity;
// Generated Oct 17, 2020 1:03:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gpu generated by hbm2java
 */
public class Gpu  implements java.io.Serializable {


     private Integer gpuId;
     private String naziv;
     private String memorija;
     private String coreCl;
     private String boostCl;
     private int tdp;
     private String imgPath;
     private Set<Konfiguracije> konfiguracijes = new HashSet<Konfiguracije>(0);

    public Gpu() {
    }

	
    public Gpu(Integer gpuId,String naziv, String memorija, String coreCl, String boostCl, int tdp, String imgPath) {
        this.naziv = naziv;
        this.memorija = memorija;
        this.coreCl = coreCl;
        this.boostCl = boostCl;
        this.tdp = tdp;
        this.imgPath = imgPath;
        this.gpuId = gpuId;
    }
    public Gpu(String naziv, String memorija, String coreCl, String boostCl, int tdp, String imgPath, Set<Konfiguracije> konfiguracijes) {
       this.naziv = naziv;
       this.memorija = memorija;
       this.coreCl = coreCl;
       this.boostCl = boostCl;
       this.tdp = tdp;
       this.imgPath = imgPath;
       this.konfiguracijes = konfiguracijes;
    }
   
    public Integer getGpuId() {
        return this.gpuId;
    }
    
    public void setGpuId(Integer gpuId) {
        this.gpuId = gpuId;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getMemorija() {
        return this.memorija;
    }
    
    public void setMemorija(String memorija) {
        this.memorija = memorija;
    }
    public String getCoreCl() {
        return this.coreCl;
    }
    
    public void setCoreCl(String coreCl) {
        this.coreCl = coreCl;
    }
    public String getBoostCl() {
        return this.boostCl;
    }
    
    public void setBoostCl(String boostCl) {
        this.boostCl = boostCl;
    }
    public int getTdp() {
        return this.tdp;
    }
    
    public void setTdp(int tdp) {
        this.tdp = tdp;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
    public Set<Konfiguracije> getKonfiguracijes() {
        return this.konfiguracijes;
    }
    
    public void setKonfiguracijes(Set<Konfiguracije> konfiguracijes) {
        this.konfiguracijes = konfiguracijes;
    }




}


