package entity;
// Generated Sep 23, 2020 12:34:30 PM by Hibernate Tools 4.3.1



/**
 * Gpu generated by hbm2java
 */
public class Gpu  implements java.io.Serializable {


     private Integer gpuId;
     private String naziv;
     private String memorija;
     private String coreCl;
     private String boostCl;
     private String imgPath;

    public Gpu() {
    }

    public Gpu(Integer gpuId,String naziv, String memorija, String coreCl, String boostCl, String imgPath) {
       this.gpuId = gpuId;
       this.naziv = naziv;
       this.memorija = memorija;
       this.coreCl = coreCl;
       this.boostCl = boostCl;
       this.imgPath = imgPath;
    }
   
    public Integer getGpuId() {
        return this.gpuId;
    }
    
    public void setGpuId(Integer gpuId) {
        this.gpuId = gpuId;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getMemorija() {
        return this.memorija;
    }
    
    public void setMemorija(String memorija) {
        this.memorija = memorija;
    }
    public String getCoreCl() {
        return this.coreCl;
    }
    
    public void setCoreCl(String coreCl) {
        this.coreCl = coreCl;
    }
    public String getBoostCl() {
        return this.boostCl;
    }
    
    public void setBoostCl(String boostCl) {
        this.boostCl = boostCl;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }




}


