package entity;
// Generated Oct 25, 2020 3:28:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Igrice generated by hbm2java
 */
public class Igrice  implements java.io.Serializable {


     private Integer igricaId;
     private Gpu gpu;
     private Procesori procesori;
     private Ram ram;
     private String igricaNaziv;
     private String imgPath;
     private Set<Igricefps> igricefpses = new HashSet<Igricefps>(0);

    public Igrice() {
    }

	
    public Igrice(Integer igricaId,Gpu gpu, Procesori procesori, Ram ram, String igricaNaziv, String imgPath) {
        this.gpu = gpu;
        this.procesori = procesori;
        this.ram = ram;
        this.igricaNaziv = igricaNaziv;
        this.imgPath = imgPath;
        this.igricaId = igricaId;
    }
    public Igrice(Gpu gpu, Procesori procesori, Ram ram, String igricaNaziv, String imgPath, Set<Igricefps> igricefpses) {
       this.gpu = gpu;
       this.procesori = procesori;
       this.ram = ram;
       this.igricaNaziv = igricaNaziv;
       this.imgPath = imgPath;
       this.igricefpses = igricefpses;
    }
   
    public Integer getIgricaId() {
        return this.igricaId;
    }
    
    public void setIgricaId(Integer igricaId) {
        this.igricaId = igricaId;
    }
    public Gpu getGpu() {
        return this.gpu;
    }
    
    public void setGpu(Gpu gpu) {
        this.gpu = gpu;
    }
    public Procesori getProcesori() {
        return this.procesori;
    }
    
    public void setProcesori(Procesori procesori) {
        this.procesori = procesori;
    }
    public Ram getRam() {
        return this.ram;
    }
    
    public void setRam(Ram ram) {
        this.ram = ram;
    }
    public String getIgricaNaziv() {
        return this.igricaNaziv;
    }
    
    public void setIgricaNaziv(String igricaNaziv) {
        this.igricaNaziv = igricaNaziv;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
    public Set<Igricefps> getIgricefpses() {
        return this.igricefpses;
    }
    
    public void setIgricefpses(Set<Igricefps> igricefpses) {
        this.igricefpses = igricefpses;
    }




}


