package entity;
// Generated Oct 22, 2020 6:02:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Komentari generated by hbm2java
 */
public class Komentari  implements java.io.Serializable {


     private Integer komentarId;
     private Konfiguracije konfiguracije;
     private Korisnici korisnici;
     private String vreme;
     private String tekst;
     private Set<Podkomentari> podkomentaris = new HashSet<Podkomentari>(0);

    public Komentari() {
    }

	
    public Komentari(Integer komentarId,Konfiguracije konfiguracije, Korisnici korisnici, String vreme, String tekst) {
        this.konfiguracije = konfiguracije;
        this.korisnici = korisnici;
        this.vreme = vreme;
        this.tekst = tekst;
        this.komentarId = komentarId;
    }
    public Komentari(Konfiguracije konfiguracije, Korisnici korisnici, String vreme, String tekst, Set<Podkomentari> podkomentaris) {
       this.konfiguracije = konfiguracije;
       this.korisnici = korisnici;
       this.vreme = vreme;
       this.tekst = tekst;
       this.podkomentaris = podkomentaris;
    }
   
    public Integer getKomentarId() {
        return this.komentarId;
    }
    
    public void setKomentarId(Integer komentarId) {
        this.komentarId = komentarId;
    }
    public Konfiguracije getKonfiguracije() {
        return this.konfiguracije;
    }
    
    public void setKonfiguracije(Konfiguracije konfiguracije) {
        this.konfiguracije = konfiguracije;
    }
    public Korisnici getKorisnici() {
        return this.korisnici;
    }
    
    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }
    public String getVreme() {
        return this.vreme;
    }
    
    public void setVreme(String vreme) {
        this.vreme = vreme;
    }
    public String getTekst() {
        return this.tekst;
    }
    
    public void setTekst(String tekst) {
        this.tekst = tekst;
    }
    public Set<Podkomentari> getPodkomentaris() {
        return this.podkomentaris;
    }
    
    public void setPodkomentaris(Set<Podkomentari> podkomentaris) {
        this.podkomentaris = podkomentaris;
    }




}


