package entity;
// Generated Sep 21, 2020 2:13:56 PM by Hibernate Tools 4.3.1



/**
 * Korisnici generated by hbm2java
 */
public class Korisnici  implements java.io.Serializable {


     private int korisnikId;
     private String ime;
     private String prezime;
     private String username;
     private String password;
     private String uloga;

    public Korisnici() {
    }

    public Korisnici(int korisnikId, String ime, String prezime, String username, String password, String uloga) {
       this.korisnikId = korisnikId;
       this.ime = ime;
       this.prezime = prezime;
       this.username = username;
       this.password = password;
       this.uloga = uloga;
    }
   
    public int getKorisnikId() {
        return this.korisnikId;
    }
    
    public void setKorisnikId(int korisnikId) {
        this.korisnikId = korisnikId;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUloga() {
        return this.uloga;
    }
    
    public void setUloga(String uloga) {
        this.uloga = uloga;
    }




}


