package entity;
// Generated Sep 21, 2020 6:33:32 PM by Hibernate Tools 4.3.1

import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.SqlResultSetMapping;




/**
 * Korisnici generated by hbm2java
 */
public class Korisnici  implements java.io.Serializable {


     private Integer korisnikId;
     private String imgPath;
     private String ime;
     private String prezime;
     private String username;
     private String password;
     private String uloga;

    public Korisnici() {
    }

    public Korisnici(String imgPath, String ime, String prezime, String username, String password, String uloga) {
       this.imgPath = imgPath;
       this.ime = ime;
       this.prezime = prezime;
       this.username = username;
       this.password = password;
       this.uloga = uloga;
    }
   
    public Integer getKorisnikId() {
        return this.korisnikId;
    }
    
    public void setKorisnikId(Integer korisnikId) {
        this.korisnikId = korisnikId;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUloga() {
        return this.uloga;
    }
    
    public void setUloga(String uloga) {
        this.uloga = uloga;
    }




}


