package entity;
// Generated Sep 23, 2020 12:34:30 PM by Hibernate Tools 4.3.1



/**
 * Kuciste generated by hbm2java
 */
public class Kuciste  implements java.io.Serializable {


     private Integer kucisteId;
     private String naziv;
     private String dimenzije;
     private String imgPath;

    public Kuciste() {
    }

    public Kuciste(Integer kucisteId,String naziv, String dimenzije, String imgPath) {
       this.kucisteId = kucisteId;
       this.naziv = naziv;
       this.dimenzije = dimenzije;
       this.imgPath = imgPath;
    }
   
    public Integer getKucisteId() {
        return this.kucisteId;
    }
    
    public void setKucisteId(Integer kucisteId) {
        this.kucisteId = kucisteId;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getDimenzije() {
        return this.dimenzije;
    }
    
    public void setDimenzije(String dimenzije) {
        this.dimenzije = dimenzije;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }




}


