package entity;
// Generated Sep 23, 2020 12:34:30 PM by Hibernate Tools 4.3.1



/**
 * Kuleri generated by hbm2java
 */
public class Kuleri  implements java.io.Serializable {


     private Integer kulerId;
     private String naziv;
     private int rpm;
     private String buka;
     private String radijatorDim;
     private String imgPath;

    public Kuleri() {
    }

	
    public Kuleri(Integer kulerId,String naziv, int rpm, String buka,String radijatorDim, String imgPath) {
        this.kulerId = kulerId;
        this.naziv = naziv;
        this.rpm = rpm;
        this.buka = buka;
        this.imgPath = imgPath;
        this.radijatorDim = radijatorDim;
    }
   
    public Integer getKulerId() {
        return this.kulerId;
    }
    
    public void setKulerId(Integer kulerId) {
        this.kulerId = kulerId;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public int getRpm() {
        return this.rpm;
    }
    
    public void setRpm(int rpm) {
        this.rpm = rpm;
    }
    public String getBuka() {
        return this.buka;
    }
    
    public void setBuka(String buka) {
        this.buka = buka;
    }
    public String getRadijatorDim() {
        return this.radijatorDim;
    }
    
    public void setRadijatorDim(String radijatorDim) {
        this.radijatorDim = radijatorDim;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }




}


