package entity;
// Generated Oct 16, 2020 5:10:00 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Podkomentari generated by hbm2java
 */
public class Podkomentari  implements java.io.Serializable {


     private Integer podkomentarId;
     private Komentari komentari;
     private Korisnici korisnici;
     private String vreme;
     private String tekst;

    public Podkomentari() {
    }

    public Podkomentari(Integer podkomentarId,Komentari komentari, Korisnici korisnici, String vreme, String tekst) {
       this.komentari = komentari;
       this.korisnici = korisnici;
       this.vreme = vreme;
       this.tekst = tekst;
       this.podkomentarId = podkomentarId;
    }
   
    public Integer getPodkomentarId() {
        return this.podkomentarId;
    }
    
    public void setPodkomentarId(Integer podkomentarId) {
        this.podkomentarId = podkomentarId;
    }
    public Komentari getKomentari() {
        return this.komentari;
    }
    
    public void setKomentari(Komentari komentari) {
        this.komentari = komentari;
    }
    public Korisnici getKorisnici() {
        return this.korisnici;
    }
    
    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }
    public String getVreme() {
        return this.vreme;
    }
    
    public void setVreme(String vreme) {
        this.vreme = vreme;
    }
    public String getTekst() {
        return this.tekst;
    }
    
    public void setTekst(String tekst) {
        this.tekst = tekst;
    }




}


