package entity;
// Generated Oct 22, 2020 6:02:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Podkomentari generated by hbm2java
 */
public class Podkomentari  implements java.io.Serializable {


     private Integer podkomentarId;
     private Komentari komentari;
     private Korisnici korisnici;
     private Podkomentari podkomentari;
     private String vreme;
     private String tekst;
     private Set<Podkomentari> podkomentaris = new HashSet<Podkomentari>(0);

    public Podkomentari() {
    }

	
    public Podkomentari(Integer podkomentarId,Komentari komentari, Korisnici korisnici,Podkomentari podkomentari, String vreme, String tekst) {
        this.komentari = komentari;
        this.korisnici = korisnici;
        this.vreme = vreme;
        this.tekst = tekst;
        this.podkomentari = podkomentari;
        this.podkomentarId = podkomentarId;
    }
    public Podkomentari(Komentari komentari, Korisnici korisnici, Podkomentari podkomentari, String vreme, String tekst, Set<Podkomentari> podkomentaris) {
       this.komentari = komentari;
       this.korisnici = korisnici;
       this.podkomentari = podkomentari;
       this.vreme = vreme;
       this.tekst = tekst;
       this.podkomentaris = podkomentaris;
    }
   
    public Integer getPodkomentarId() {
        return this.podkomentarId;
    }
    
    public void setPodkomentarId(Integer podkomentarId) {
        this.podkomentarId = podkomentarId;
    }
    public Komentari getKomentari() {
        return this.komentari;
    }
    
    public void setKomentari(Komentari komentari) {
        this.komentari = komentari;
    }
    public Korisnici getKorisnici() {
        return this.korisnici;
    }
    
    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }
    public Podkomentari getPodkomentari() {
        return this.podkomentari;
    }
    
    public void setPodkomentari(Podkomentari podkomentari) {
        this.podkomentari = podkomentari;
    }
    public String getVreme() {
        return this.vreme;
    }
    
    public void setVreme(String vreme) {
        this.vreme = vreme;
    }
    public String getTekst() {
        return this.tekst;
    }
    
    public void setTekst(String tekst) {
        this.tekst = tekst;
    }
    public Set<Podkomentari> getPodkomentaris() {
        return this.podkomentaris;
    }
    
    public void setPodkomentaris(Set<Podkomentari> podkomentaris) {
        this.podkomentaris = podkomentaris;
    }




}


