package entity;
// Generated Oct 22, 2020 6:02:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Porukekorisnika generated by hbm2java
 */
public class Porukekorisnika  implements java.io.Serializable {


     private Integer porukaKorisnikaId;
     private Korisnici korisnici;
     private String vreme;
     private String tekst;
     private String odgovoreno;
     private Set<Porukeurednika> porukeurednikas = new HashSet<Porukeurednika>(0);

    public Porukekorisnika() {
    }

	
    public Porukekorisnika(Integer porukaKorisnikaId, Korisnici korisnici, String vreme, String tekst,String odgovoreno) {
        this.porukaKorisnikaId = porukaKorisnikaId;
        this.korisnici = korisnici;
        this.vreme = vreme;
        this.tekst = tekst;
        this.odgovoreno = odgovoreno;
    }
    public Porukekorisnika(Integer porukaKorisnikaId, Korisnici korisnici, String vreme, String tekst,String odgovoreno, Set<Porukeurednika> porukeurednikas) {
       this.porukaKorisnikaId = porukaKorisnikaId;
       this.korisnici = korisnici;
       this.vreme = vreme;
       this.tekst = tekst;
       this.odgovoreno = odgovoreno;
       this.porukeurednikas = porukeurednikas;
    }
   
    public Integer getPorukaKorisnikaId() {
        return this.porukaKorisnikaId;
    }
    
    public void setPorukaKorisnikaId(Integer porukaKorisnikaId) {
        this.porukaKorisnikaId = porukaKorisnikaId;
    }
    public Korisnici getKorisnici() {
        return this.korisnici;
    }
    
    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }
    public String getVreme() {
        return this.vreme;
    }
    
    public void setVreme(String vreme) {
        this.vreme = vreme;
    }
    public String getTekst() {
        return this.tekst;
    }
    
    public void setTekst(String tekst) {
        this.tekst = tekst;
    }
    
    public String getOdgovoreno() {
        return this.odgovoreno;
    }
    
    public void setOdgovoreno(String odgovoreno) {
        this.odgovoreno = odgovoreno;
    }
    public Set<Porukeurednika> getPorukeurednikas() {
        return this.porukeurednikas;
    }
    
    public void setPorukeurednikas(Set<Porukeurednika> porukeurednikas) {
        this.porukeurednikas = porukeurednikas;
    }




}


