package entity;
// Generated Oct 25, 2020 3:28:51 PM by Hibernate Tools 4.3.1



/**
 * Porukeurednika generated by hbm2java
 */
public class Porukeurednika  implements java.io.Serializable {


     private Integer porukaUrednikId;
     private Korisnici korisnici;
     private Porukekorisnika porukekorisnika;
     private String vreme;
     private String tekst;

    public Porukeurednika() {
    }

    public Porukeurednika(Integer porukaUrednikId,Korisnici korisnici, Porukekorisnika porukekorisnika, String vreme, String tekst) {
       this.korisnici = korisnici;
       this.porukekorisnika = porukekorisnika;
       this.vreme = vreme;
       this.tekst = tekst;
       this.porukaUrednikId = porukaUrednikId;
    }
   
    public Integer getPorukaUrednikId() {
        return this.porukaUrednikId;
    }
    
    public void setPorukaUrednikId(Integer porukaUrednikId) {
        this.porukaUrednikId = porukaUrednikId;
    }
    public Korisnici getKorisnici() {
        return this.korisnici;
    }
    
    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }
    public Porukekorisnika getPorukekorisnika() {
        return this.porukekorisnika;
    }
    
    public void setPorukekorisnika(Porukekorisnika porukekorisnika) {
        this.porukekorisnika = porukekorisnika;
    }
    public String getVreme() {
        return this.vreme;
    }
    
    public void setVreme(String vreme) {
        this.vreme = vreme;
    }
    public String getTekst() {
        return this.tekst;
    }
    
    public void setTekst(String tekst) {
        this.tekst = tekst;
    }




}


