package entity;
// Generated Oct 17, 2020 1:03:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Procesori generated by hbm2java
 */
public class Procesori  implements java.io.Serializable {


     private Integer procesorId;
     private int brojJezgara;
     private String frekvencija;
     private String boost;
     private int tdp;
     private String igpu;
     private String naziv;
     private String socket;
     private String imgPath;
     private Set<Konfiguracije> konfiguracijes = new HashSet<Konfiguracije>(0);

    public Procesori() {
    }

	
    public Procesori(Integer procesorId,int brojJezgara, String frekvencija, String boost, int tdp, String igpu, String naziv, String socket, String imgPath) {
        this.brojJezgara = brojJezgara;
        this.frekvencija = frekvencija;
        this.boost = boost;
        this.tdp = tdp;
        this.igpu = igpu;
        this.naziv = naziv;
        this.socket = socket;
        this.imgPath = imgPath;
        this.procesorId = procesorId;
    }
    public Procesori(int brojJezgara, String frekvencija, String boost, int tdp, String igpu, String naziv, String socket, String imgPath, Set<Konfiguracije> konfiguracijes) {
       this.brojJezgara = brojJezgara;
       this.frekvencija = frekvencija;
       this.boost = boost;
       this.tdp = tdp;
       this.igpu = igpu;
       this.naziv = naziv;
       this.socket = socket;
       this.imgPath = imgPath;
       this.konfiguracijes = konfiguracijes;
    }
   
    public Integer getProcesorId() {
        return this.procesorId;
    }
    
    public void setProcesorId(Integer procesorId) {
        this.procesorId = procesorId;
    }
    public int getBrojJezgara() {
        return this.brojJezgara;
    }
    
    public void setBrojJezgara(int brojJezgara) {
        this.brojJezgara = brojJezgara;
    }
    public String getFrekvencija() {
        return this.frekvencija;
    }
    
    public void setFrekvencija(String frekvencija) {
        this.frekvencija = frekvencija;
    }
    public String getBoost() {
        return this.boost;
    }
    
    public void setBoost(String boost) {
        this.boost = boost;
    }
    public int getTdp() {
        return this.tdp;
    }
    
    public void setTdp(int tdp) {
        this.tdp = tdp;
    }
    public String getIgpu() {
        return this.igpu;
    }
    
    public void setIgpu(String igpu) {
        this.igpu = igpu;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getSocket() {
        return this.socket;
    }
    
    public void setSocket(String socket) {
        this.socket = socket;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
    public Set<Konfiguracije> getKonfiguracijes() {
        return this.konfiguracijes;
    }
    
    public void setKonfiguracijes(Set<Konfiguracije> konfiguracijes) {
        this.konfiguracijes = konfiguracijes;
    }




}


