package entity;
// Generated Sep 23, 2020 12:34:30 PM by Hibernate Tools 4.3.1



/**
 * Psu generated by hbm2java
 */
public class Psu  implements java.io.Serializable {


     private Integer psuId;
     private String naziv;
     private String efikasnost;
     private String jacina;
     private String modularnost;
     private String imgPath;

    public Psu() {
    }

    public Psu(Integer psuId,String naziv, String efikasnost, String jacina, String modularnost, String imgPath) {
       this.psuId = psuId;
       this.naziv = naziv;
       this.efikasnost = efikasnost;
       this.jacina = jacina;
       this.modularnost = modularnost;
       this.imgPath = imgPath;
    }
   
    public Integer getPsuId() {
        return this.psuId;
    }
    
    public void setPsuId(Integer psuId) {
        this.psuId = psuId;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getEfikasnost() {
        return this.efikasnost;
    }
    
    public void setEfikasnost(String efikasnost) {
        this.efikasnost = efikasnost;
    }
    public String getJacina() {
        return this.jacina;
    }
    
    public void setJacina(String jacina) {
        this.jacina = jacina;
    }
    public String getModularnost() {
        return this.modularnost;
    }
    
    public void setModularnost(String modularnost) {
        this.modularnost = modularnost;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }




}


