package entity;
// Generated Oct 16, 2020 5:10:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Psu generated by hbm2java
 */
public class Psu  implements java.io.Serializable {


     private Integer psuId;
     private String naziv;
     private String efikasnost;
     private int jacina;
     private String modularnost;
     private String imgPath;
     private Set<Konfiguracije> konfiguracijes = new HashSet<Konfiguracije>(0);

    public Psu() {
    }

	
    public Psu(Integer psuId,String naziv, String efikasnost, int jacina, String modularnost, String imgPath) {
        this.naziv = naziv;
        this.efikasnost = efikasnost;
        this.jacina = jacina;
        this.modularnost = modularnost;
        this.imgPath = imgPath;
        this.psuId = psuId;
    }
    public Psu(String naziv, String efikasnost, int jacina, String modularnost, String imgPath, Set<Konfiguracije> konfiguracijes) {
       this.naziv = naziv;
       this.efikasnost = efikasnost;
       this.jacina = jacina;
       this.modularnost = modularnost;
       this.imgPath = imgPath;
       this.konfiguracijes = konfiguracijes;
    }
   
    public Integer getPsuId() {
        return this.psuId;
    }
    
    public void setPsuId(Integer psuId) {
        this.psuId = psuId;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getEfikasnost() {
        return this.efikasnost;
    }
    
    public void setEfikasnost(String efikasnost) {
        this.efikasnost = efikasnost;
    }
    public int getJacina() {
        return this.jacina;
    }
    
    public void setJacina(int jacina) {
        this.jacina = jacina;
    }
    public String getModularnost() {
        return this.modularnost;
    }
    
    public void setModularnost(String modularnost) {
        this.modularnost = modularnost;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
    public Set<Konfiguracije> getKonfiguracijes() {
        return this.konfiguracijes;
    }
    
    public void setKonfiguracijes(Set<Konfiguracije> konfiguracijes) {
        this.konfiguracijes = konfiguracijes;
    }




}


