package entity;
// Generated Sep 23, 2020 12:34:30 PM by Hibernate Tools 4.3.1



/**
 * Ram generated by hbm2java
 */
public class Ram  implements java.io.Serializable {


     private Integer ramId;
     private String naziv;
     private String brzina;
     private int casLat;
     private String imgPath;

    public Ram() {
    }

    public Ram(Integer ramId,String naziv, String brzina, int casLat, String imgPath) {
       this.ramId = ramId;
       this.naziv = naziv;
       this.brzina = brzina;
       this.casLat = casLat;
       this.imgPath = imgPath;
    }
   
    public Integer getRamId() {
        return this.ramId;
    }
    
    public void setRamId(Integer ramId) {
        this.ramId = ramId;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getBrzina() {
        return this.brzina;
    }
    
    public void setBrzina(String brzina) {
        this.brzina = brzina;
    }
    public int getCasLat() {
        return this.casLat;
    }
    
    public void setCasLat(int casLat) {
        this.casLat = casLat;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }




}


